services:
  web:
    depends_on:
      - api

    build: ./client

    env_file: ./.env

    ports:
      - 5173:5173

    develop:
      watch:
        - path: ./client/package.json
          x-initialSync: true
          action: rebuild
        - path: ./client/package-lock.json
          x-initialSync: true
          action: rebuild

        - path: ./client
          x-initialSync: true
          target: /app
          action: sync

  api:
    depends_on:
      - redis
    build: ./server

    ports:
      - 8000:8000

    develop:
      watch:
        - path: ./server/package.json
          x-initialSync: true
          action: rebuild
        - path: ./server/package-lock.json
          x-initialSync: true
          action: rebuild

        - path: ./server
          x-initialSync: true
          target: /app
          action: rebuild

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: map
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 12345:3306
    env_file:
      - ./.env

  redis:
    depends_on:
      - db
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    env_file:
      - ./.env

volumes:
  db_data:
